export const HEAT_CONFIG = {
  GRID_X: 16,
  GRID_Y: 24,
  GRID_Z: 8,
  AMBIENT_TEMP: 25.0,
  MAX_TEMP: 150.0,
  WARNING_TEMP: 85.0,
  CRITICAL_TEMP: 120.0,
  MELTDOWN_TEMP: 140.0,

  THYRISTOR_RESISTANCE: 0.0015,
  THYRISTOR_CURRENT: 4000,
  I2R_HEAT_SCALE: 0.0008,

  DIFFUSIVITY_THYRISTOR: 0.12,
  DIFFUSIVITY_ALUMINUM: 1.2,
  DIFFUSIVITY_COOLANT: 0.6,
  DIFFUSIVITY_INSULATOR: 0.02,
  DIFFUSIVITY_AIR: 0.005,

  CONVECTION_COEFF: 0.02,
  COOLANT_FLOW_RATE: 0.15,
  COOLANT_INLET_TEMP: 22.0,

  DT: 0.016,
  STEPS_PER_FRAME: 3,
  CFL_SAFETY: 0.4,

  THERMAL_MAP_RESOLUTION: 256,
  EMISSIVE_BOOST: 1.5
}

export const MATERIAL_TYPE = {
  AIR: 0,
  THYRISTOR: 1,
  ALUMINUM_HEATSINK: 2,
  COOLANT_PIPE: 3,
  INSULATOR: 4,
  FRAME: 5
}

export const HEAT_MESSAGE_TYPE = {
  INIT: 'heat_init',
  STEP: 'heat_step',
  INJECT_HEAT: 'heat_inject',
  SET_COOLANT_FLOW: 'heat_coolant_flow',
  SET_SIMULATION_SPEED: 'heat_sim_speed',
  GET_TEMPERATURE: 'heat_get_temp',
  WARNING: 'heat_warning',
  STATS: 'heat_stats',
  DISPOSE: 'heat_dispose'
}

export const WARNING_LEVEL = {
  NORMAL: 0,
  CAUTION: 1,
  WARNING: 2,
  CRITICAL: 3,
  MELTDOWN: 4
}
